### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by angieherrera** [emandiev/regex-replace-twig-filter#1]
Hi! Will this plugin work with Craft 4? Not seeing it in the plugin store for Craft 4.

**Comment by chadcrowell** [comment]
Just added pull request #2 for Craft 4 compatibility. Tested locally working fine.

**Comment by angieherrera** [comment]
Hey @chadcrowell! Have you by any chance tested your PR on production? This is the one plugin that's holding up a particular Craft 4 update for me.

**Comment by chadcrowell** [comment]
Hi Angie - No but I have tested it on the production branch of my local dev env with no issues. It really was literally the easiest plugin migration from 3 > 4 I've done, and it was done with the Craft 4 Rector package. If you look at the [commit](https://github.com/emandiev/regex-replace-twig-filter/pull/2/commits/bc67a6942ab8cfa28369fc241d2f6fbae0ce9148), you can see how simple it was.

**Comment by outline4** [comment]
I would need the Craft 4 version. Unluckily I had no chance loading it into craft, and I am an absolute noob in the github space... Could anyone guide me on how to get this to work for craft 4?

**Comment by emandiev** [comment]
Thanks for the effort comrades!  
I just merged the file changes 🎉
